export const DATABASE_PORT = Number(process.env.DATABASE_PORT)
export const DATABASE_NAME = String(process.env.DATABASE_NAME)
export const DATABASE_HOST = String(process.env.DATABASE_HOST)
export const DATABASE_USERNAME = String(process.env.DATABASE_USERNAME)
export const DATABASE_PASSWORD = String(process.env.DATABASE_PASSWORD)
